/// Flutter icons ChessClient
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  ChessClient
///      fonts:
///       - asset: fonts/ChessClient.ttf
///
///
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class ChessClient {
  ChessClient._();

  static const _kFontFam = 'ChessClient';
  static const String _kFontPkg = null;

  static const IconData arrow_back =
      IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData swap_vert =
      IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData check_circle =
      IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cancel =
      IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData keyboard_arrow_left =
      IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData keyboard_arrow_right =
      IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData restore =
      IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chess_bishop =
      IconData(0xf43a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chess_king =
      IconData(0xf43f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chess_knight =
      IconData(0xf441, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chess_pawn =
      IconData(0xf443, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chess_queen =
      IconData(0xf445, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chess_rook =
      IconData(0xf447, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
